version:  '3.7'

services:
  dcc-verifier-api:
    container_name: dcc-verifier-api
    image: grambas/dcc-verifier-api:8.1
#    build:
#      context: ./php
#      dockerfile: Dockerfile81
#    user: www-data
    environment:
      PHP_IDE_CONFIG: 'serverName=ddc-verifier-api'
    volumes:
      - ./:/srv/:rw,cached
      # for better performance by enabling the next line
      # - /srv/app/var
      - ./php/dev.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dcc-verifier-api-nginx:
    image: nginx:1.15.3-alpine
    container_name: dcc-verifier-api-nginx
    restart: on-failure
    ports:
      - "81:80"
    volumes:
      - ./:/srv/:cached
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dcc-verifier-api

  mailer:
    image: schickling/mailcatcher
    restart: unless-stopped
    ports:
      - "1026:1026"
      - "1081:1080" # web interface, use MAILER_DSN=smtp://mailer:1026
